apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.srvPort }}
      targetPort: http
  selector:
    app: {{ .Values.name }}
  type: ClusterIP